Fixed typos errors - update test.md
mandiant/flare-floss pull request #676
Opened 2023-04-03 15:33 UTC by EmperialX

Fixed typos and spelling errors in [test.md](https://github.com/mandiant/flare-floss/blob/master/doc/test.md)

2023-04-03 18:02 UTC, mr-tz commented on doc/test.md
> +  - Decide on a name for your test. Pick something like "decode-rot-13." Follow the examples and stick to this name throughout the test case.
```suggestion
  - Decide on a name for your test. Pick something like `decode-rot-13`. Follow the examples and stick to this name throughout the test case.
```

2023-04-03 18:58 UTC, EmperialX commented
@mr-tz i remove the commit for test.yml

2023-04-04 11:41 UTC, mr-tz approved these changes
thanks

2023-04-04 11:42 UTC, mr-tz requested changes
oh wait, we don't want to remove tests.yml, just the change to it

2023-04-04 16:59 UTC, EmperialX commented
@mr-tz done .

2023-04-04 20:23 UTC, EmperialX commented
@mr-tz please check now is there any error. thank you

2023-04-04 20:30 UTC, symbolicvoid commented
Hey @mr-tz @EmperialX Do we really want to remove the newlines between the text from the file? I found it helpful when editing the docs in pycharm as it displays how the file would look and shortens the file source itself.

2023-04-05 06:44 UTC, mr-tz commented on doc/test.md
> +  - Move `cd` to `tests/data/src/decode-rot-13` and run `make all`. Confirm the binary runs as expected.
```suggestion
  - `cd` to `tests/data/src/decode-rot-13` and run `make all`. Confirm the binary runs as expected.
```

2023-04-05 06:46 UTC, mr-tz commented
I like the simplification and fixes here. Plus the rendered output (which most people see) doesn't change. I appreciate you raising your concerns here though.

2023-04-05 06:46 UTC, merged

2023-04-05 08:01 UTC, symbolicvoid commented
@mr-tz I like the fixes too. But I just wanted to raise concern about the doc becoming a bit harder to edit. I could convey it better with images. This is how the file looked in pycharm before the removal of newlines:

![image_2023-04-05_132337679](https://user-images.githubusercontent.com/126584775/230016974-20a07de3-3fa4-4312-a2c6-65f1db1c9338.png)
Most of the lines are visible and editable without having to scroll sideways.

 This is how it looks after:

![image_2023-04-05_132542831](https://user-images.githubusercontent.com/126584775/230017487-dcd47e5f-e56c-4dd5-b05a-cd58b4859985.png)

You will have to scroll sideways for most of these lines. This is just an inconvenience when editing this file, as the display remains the same, but I don't see the benefits for doing this either. Apologies if I am making a way bigger issue of it than it has to be, I do appreciate the typo fixes.

2023-04-05 10:58 UTC, mr-tz commented
Gotcha, does Pycharm support word wrapping in the editor?

2023-04-05 11:29 UTC, symbolicvoid commented
Ah it does support soft wraps. That should be good enough, apologies for this.

2023-04-06 07:59 UTC, mr-tz commented
No worries, I think originally this was written exactly for the reason you mentioned.