Extract Rust specific strings from binaries #791
mandiant/flare-floss pull request #836
Opened 2023-07-17 19:05 UTC by Arker123

This pull request introduces a new feature to extract Rust specific strings from binaries.
Solves: #791

2023-07-17 19:05 UTC, Arker123 commented
There are still several tasks pending, such as updating references from source code, comments, etc. Therefore, I'm marking this pull request as a draft for now.

2023-07-18 07:10 UTC, mr-tz commented
On first glance this appears to be identical or very close to the Go extract script. Can we just reuse that code or functions from it, so we don't repeat the same code twice?

2023-07-28 07:33 UTC, Arker123 commented
> On first glance this appears to be identical or very close to the Go extract script. Can we just reuse that code or functions from it, so we don't repeat the same code twice?

Agreed! Let's consolidate the code and reuse the functions from the Go extract script in a separate PR after merging this one. We can create a file something like `language/utils.py` to house the shared functions. Thanks for the suggestion!

2023-07-28 07:38 UTC, Arker123 commented
The current algorithm is based on pull request https://github.com/mandiant/flare-floss/issues/791#issuecomment-1654070181, and it's progressing well.
TODO: Extract references from the .text segment as well and improve code style and comments.

On a positive note, the algorithm appears to be splitting the strings quite effectively, as shown in the attached image.
![image](https://github.com/mandiant/flare-floss/assets/94680887/09936287-c63c-4426-a40c-cbec99825659)
![image](https://github.com/mandiant/flare-floss/assets/94680887/dcbb5932-f03d-45c7-a79c-1ffa4a04c9a8)

2023-08-05 06:39 UTC, Arker123 commented
TODO: Refactor comments and type hints

2023-08-05 09:06 UTC, Arker123 commented
The current outcome appears promising.
![image](https://github.com/mandiant/flare-floss/assets/94680887/d624df9e-3407-4541-9469-20a443dae35f)

2023-08-07 13:00 UTC, mr-tz requested changes

2023-08-07 13:16 UTC, mr-tz commented on floss/language/rust/extract.py
> +    ref_data = filter_strings(strings, start_rdata, end_rdata)
which is done already, so is the filter needed?

2023-08-07 13:19 UTC, mr-tz commented on floss/language/rust/extract.py
> +            string = StaticString.from_utf8(ref[0].replace("\n", "").encode("utf-8"), ref[1], min_length)
need to be consistent here with handling the `\n` like we do elsewhere

2023-08-14 08:23 UTC, mr-tz requested changes

2023-08-14 08:23 UTC, mr-tz commented on floss/language/rust/coverage.py
> +    rust_strings = extract_utf8_strings(path, args.min_length)
don't we want the extracted rust strings here?

2023-08-14 08:23 UTC, mr-tz commented on floss/language/rust/coverage.py
> +            print(string.encode("utf-8"))
there shouldn't be extra output here, maybe use logger.debug() to show the data if needed

2023-08-14 08:23 UTC, mr-tz commented on floss/language/rust/coverage.py
> +def get_extract_stats(static_strings: Iterable[StaticString], rust_strings: List[StaticString]) -> str:
seems to be resolved now

2023-08-14 08:23 UTC, mr-tz commented on floss/language/rust/coverage.py
> +        large_chunk += string
Concatenating all strings here and then checking the rust strings below seems cumbersome and could result in found strings which should actually be split. Can you tweak this to search/compare properly?

2023-08-14 08:23 UTC, mr-tz commented on floss/language/rust/extract.py
> +            break
No, if we sys.exit here, this cannot be used easily as a library by other programs. Instead, raise a custom exception and catch where this is called.

2023-08-14 08:23 UTC, mr-tz commented on floss/language/rust/extract.py
> +    # start_rdata, end_rdata, virtual_address, pointer_to_raw_data = get_rdata_section_info(pe)
```suggestion
```

2023-08-14 08:23 UTC, mr-tz commented on floss/language/rust/extract.py
> +        split_string(ref_data, address)
TODO

2023-08-14 08:23 UTC, mr-tz commented on floss/language/rust/extract.py
> +def filter_strings_utf8(strings: List[Tuple[str, str, Tuple[int, int], bool]], start_rdata: int) -> List[Strings]:
this filters and returns modified data (start, end), so better change name or add a separate function?

2023-08-14 10:54 UTC, mr-tz commented on floss/language/rust/coverage.py
> +        large_chunk += string
as a reference, we have the Go coverage script, but I think you should think about the algorithm a bit first and suggest something

2023-08-16 08:14 UTC, mr-tz commented on floss/language/rust/coverage.py
> +    arrs = parser.parse_arrs()
`parse_args`?

2023-08-16 08:14 UTC, mr-tz commented on floss/language/rust/coverage.py
> +def get_extract_stats(pe, all_ss_strings: List[StaticString], rust_strings, min_len) -> float:
if this is the same (or almost) as Go, can we reuse that and not duplicate all of the code?

2023-08-16 08:14 UTC, mr-tz commented on floss/language/rust/extract.py
> +        split_string(ref_data, address)
I'd imagine something like below in a block. Does that make sense?
```python
    substring = split_string(ref_data, address)
    string = StaticString.from_utf8(...)
    static_strings.append(string)
```

2023-08-17 17:57 UTC, mr-tz commented on .github/mypy/mypy.ini
> +
```suggestion
```

2023-08-17 17:57 UTC, mr-tz commented on floss/language/rust/extract.py
> +        return rdata_structure
should this be returned here and can you double check the initialization in line 30 is what you want in this function?

2023-08-17 17:57 UTC, mr-tz commented on floss/language/rust/extract.py
> +    """
```suggestion
```

2023-08-17 17:57 UTC, mr-tz commented on floss/language/rust/coverage.py
> +    get_extract_stats(pe, static_strings, rust_strings, args.min_length, 0)
does the 0 argument make sense here?

2023-08-17 17:59 UTC, mr-tz commented
> > I'd imagine something like below in a block. Does that make sense?
> 
> Sure thing! I get your point. Consider this: If the string is "CatDogHorse" and string pointers are at the end of each word, we'd have "CatDog" and "Horse" as splits. So, multiple splits are possible for a string. So, before adding to the static string, I think it's best to split all possible substrings. This way, we cover all potential splits. What do you think?

I'm not sure I follow. Do you have an example binary and output for this?

2023-08-21 08:52 UTC, mr-tz commented on floss/language/rust/extract.py
> +        split_string(ref_data, address)
Your comment in https://github.com/mandiant/flare-floss/pull/836#issuecomment-1684935367 doesn't clarify things for me really, but regardless, this more a comment on the design. The function can return a single string or if needed a list of strings that have been split. Does that make sense?

2023-08-21 16:27 UTC, mr-tz commented on floss/language/rust/extract.py
> +def split_string(ref_data: List[Strings], static_strings: List[StaticString], address: int) -> None:
how about returning `List[StaticString]` here?

2023-08-21 16:28 UTC, mr-tz commented on floss/language/rust/extract.py
> +            pass
we shouldn't affect the coverage, but come up with a clean and easy to follow design

2023-08-22 09:29 UTC, mr-tz commented on floss/language/rust/extract.py
> +        logger.error("No .rdata section found")
raise exception here and catch where called

2023-08-22 09:29 UTC, mr-tz commented on floss/language/rust/extract.py
> +    filter_and_transform_utf8_strings(strings, static_strings, start_rdata, min_length)
return value here

2023-08-22 09:30 UTC, mr-tz commented on floss/results.py
> +    def from_utf8(cls, buf, addr, min_length: int, end_addr: Optional[int] = None):
we can calculate this from addr + len(string)

2023-08-22 11:19 UTC, mr-tz commented on floss/language/rust/extract.py
> +        address = can.address - image_base - virtual_address + pointer_to_raw_data
this is the virtual address not the raw offset in the file

2023-08-22 11:27 UTC, mr-tz commented on floss/language/rust/extract.py
> +        address = can.address - image_base - virtual_address + pointer_to_raw_data
nevermind, was looking at the wrong file

2023-08-22 12:00 UTC, mr-tz commented on floss/language/rust/extract.py
> +        address = can.address - image_base - virtual_address + pointer_to_raw_data
Can you double-check the static strings FLOSS output lines up with this?

2023-08-22 18:16 UTC, mr-tz commented on floss/language/rust/coverage.py
> +    get_extract_stats(pe, static_strings, rust_strings, args.min_length, 0)
this is still an open question, we should add least add a comment with an explanation here

2023-08-22 18:18 UTC, mr-tz reviewed
sorry, I think I didn't properly format my changes (in the PR to the fork)

2023-08-23 08:48 UTC, mr-tz commented on floss/language/rust/extract.py
> +    xrefs_mov = find_mov_xrefs(pe)
do we want to do all of these all the time (for both architectures or specific to 32/64 bit?)

2023-08-23 08:49 UTC, mr-tz commented on floss/language/rust/extract.py
can you please share some current coverage output for 32 and 64 bit samples?

2023-08-23 08:53 UTC, mr-tz commented on floss/language/rust/coverage.py
> +    get_extract_stats(pe, static_strings, rust_strings, args.min_length, 0)
@Arker123 ^^

2023-08-23 09:07 UTC, mr-tz commented on floss/language/rust/extract.py
can you repeat this for a few random samples and just share the stats here?

2023-08-23 09:18 UTC, mr-tz commented on floss/language/utils.py
> +            xrefs: Iterable[VA] = []  # no push instructions on amd64
can we be sure string references would never be pushed? probably, but can you add some context/references around this? the comment is a little misleading currently

2023-08-23 09:20 UTC, mr-tz commented on floss/language/utils.py
> +            xrefs: Iterable[VA] = []  # no mov instructions on amd64
same comment as above

2023-08-23 09:22 UTC, mr-tz commented on floss/language/rust/extract.py
great, that looks pretty promising!

2023-08-23 11:36 UTC, mr-tz commented on floss/language/utils.py
> +    # while in case of Go extraction, we want to extract only large strings (len > 2800) from binary file
let's only leave the respective comments where this is called, so please remove here

2023-08-23 12:13 UTC, merged