Test the detection of known Go binaries
mandiant/flare-floss pull request #845
Opened 2023-07-26 06:05 UTC by Arker123

This PR includes tests to verify the detection of known strings in various versions of Go binaries, which are extracted from zip archives.

2023-07-26 06:07 UTC, Arker123 commented
Once #842 is merged, let's proceed with merging this.

2023-08-01 13:56 UTC, williballenthin commented on tests/test_language_go_known_binary.py
> +    print(extracted_files)
```suggestion
```

2023-08-01 13:57 UTC, williballenthin commented on tests/test_language_go_known_binary.py
> +            print(extracted_file_path)
```suggestion
```

2023-08-01 13:57 UTC, williballenthin commented on tests/test_language_go_known_binary.py
> +    print(extracted_files)
```suggestion
```

2023-08-01 13:59 UTC, williballenthin requested changes
remove debugging `print` statements and then ready to go

2023-08-07 11:28 UTC, mr-tz requested changes

2023-08-07 11:28 UTC, mr-tz commented on tests/test_language_go_known_binary.py
> +def extract_files_32():
can you unify this and `extract_files_64` be into one function?

2023-08-07 11:28 UTC, mr-tz commented on tests/test_language_go_known_binary.py
> +def test_language_detection_32(binary_file, extract_files_32):
these test names don't appear to be indicating what's actually tested here, please update them

2023-08-09 08:17 UTC, mr-tz approved these changes
great, thanks!

2023-08-09 08:17 UTC, merged